name: 'tests'
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  tests:
    strategy:
      matrix:
        node_version: [ '12', '14', '16' ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: use cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
